# Mobile App for Lottery Addiction

- The project is related to addictions faced by people who become addicted towards lottery. Lottery addicts like compulsive gamblers start to burn through their savings and accumulate debts which in return brings many problems.
- Our goal is to help a team of engineers of a medical institute build the app and for that, we need to create the logical core of the app. This includes helping the lottery addicts estimate their chances of winning.
- For this project, we will take into consideration [historical data](https://www.kaggle.com/datascienceai/lottery-dataset) from the national 6/49 lottery game in Canada.
- The app idea comes from a medical institute which is specialized in treating gambling addictions. The institute already has a team of engineers that will build the app, but they need us to create the logical core of the app and calculate probabilities. For the first version of the app, they want us to focus on the 6/49 lottery and build functions that can answer users the following questions:

    - What is the probability of winning the big prize with a single ticket?
    - What is the probability of winning the big prize if we play 40 different tickets (or any other number)?
    - What is the probability of having at least five (or four, or three) winning numbers on a single ticket?
    
- The scenario we're following throughout this project is fictional — the main purpose is to practice applying probability and combinatorics (permutations and combinations) concepts in a setting that simulates a real-world scenario.

## Core Functions

Below, we're going to write two functions that we'll be using frequently:

- `factorial()` — a function that calculates factorials
- `combinations()` — a function that calculates combinations

In [32]:
# Creating a new function: factorial
def factorial(n):
    product = 1
    for i in range(1,n+1):
        product *= i
    return product

In [33]:
def combinations(n,k):
    return factorial(n) / (factorial(k) * factorial(n-k))

## One-ticket Probability

We need to build a function that calculates the probability of winning the big prize for any given ticket. For each drawing, six numbers are drawn from a set of 49, and a player wins the big prize if the six numbers on their tickets match all six numbers.

The engineer team told us that we need to be aware of the following details when we write the function:

- Inside the app, the user inputs six different numbers from 1 to 49.
- Under the hood, the six numbers will come as a Python list and serve as an input to our function.
- The engineering team wants the function to print the probability value in a friendly way — in a way that people without any probability training are able to understand.

Below, we write the `one_ticket_probability()` function, which takes in a list of six unique numbers and prints the probability of winning in a way that's easy to understand.

In [34]:
def one_ticket_probability(l):
    possible_outcomes = combinations(49, 6)
    probability = 1 / possible_outcomes
    return "You have {:.7f}% chances of winning with {} ticket numbers. In other words, you have 1 in {:,} chances of winning".format(probability*100, l, int(possible_outcomes))

We'll test our function now as to see the result.

In [35]:
# Trial 1
one_ticket_probability([2,5,6,45,34,23])

'You have 0.0000072% chances of winning with [2, 5, 6, 45, 34, 23] ticket numbers. In other words, you have 1 in 13,983,816 chances of winning'

In [36]:
# Trial 2
one_ticket_probability([5,32,1,9,6,48])

'You have 0.0000072% chances of winning with [5, 32, 1, 9, 6, 48] ticket numbers. In other words, you have 1 in 13,983,816 chances of winning'

## Historical Data Check for Canada Lottery

The institute also wants us to consider the data coming from the national 6/49 lottery game in Canada. The data set contains historical data for 3,665 drawings, dating from 1982 to 2018.

In [37]:
# Importing relevant libraries
import pandas as pd

In [38]:
# Read in the data set
lottery_649 = pd.read_csv('649.csv')

In [39]:
# Checking the shape of dataframe
lottery_649.shape

(3665, 11)

We have 3665 rows and 11 columns in our dataset

In [40]:
# Printing out first 3 rows
lottery_649.head(3)

PRODUCT  DRAW NUMBER  SEQUENCE NUMBER  DRAW DATE  NUMBER DRAWN 1  \
0      649            1                0  6/12/1982               3   
1      649            2                0  6/19/1982               8   
2      649            3                0  6/26/1982               1   

   NUMBER DRAWN 2  NUMBER DRAWN 3  NUMBER DRAWN 4  NUMBER DRAWN 5  \
0              11              12              14              41   
1              33              36              37              39   
2               6              23              24              27   

   NUMBER DRAWN 6  BONUS NUMBER  
0              43            13  
1              41             9  
2              39            34

In [41]:
# Printing out last 3 rows
lottery_649.tail(3)

PRODUCT  DRAW NUMBER  SEQUENCE NUMBER  DRAW DATE  NUMBER DRAWN 1  \
3662      649         3589                0  6/13/2018               6   
3663      649         3590                0  6/16/2018               2   
3664      649         3591                0  6/20/2018              14   

      NUMBER DRAWN 2  NUMBER DRAWN 3  NUMBER DRAWN 4  NUMBER DRAWN 5  \
3662              22              24              31              32   
3663              15              21              31              38   
3664              24              31              35              37   

      NUMBER DRAWN 6  BONUS NUMBER  
3662              34            16  
3663              49             8  
3664              48            17

## Function for Historical Data Check

The engineering team tells us that we need to write a function that can help users determine whether they would have ever won by now using a certain combination of six numbers. These are the details we'll need to be aware of:

- Inside the app, the user inputs six different numbers from 1 to 49.
- Under the hood, the six numbers will come as a Python list and serve as an input to our function.
- The engineering team wants us to write a function that prints:
    - the number of times the combination selected occurred; and
    - the probability of winning the big prize in the next drawing with that combination.
    

We're going to begin by extracting all the winning numbers from the lottery data set. The `extract_numbers()` function will go over each row of the dataframe and extract the six winning numbers as a Python set.

In [53]:
def extract_numbers(row):
    row = row[4:10]
    row = set(row.values)
    return row

In [54]:
# Creating column 'ticket' using extract_numbers function
lottery_649['ticket'] = lottery_649.apply(extract_numbers, axis=1)

In [56]:
lottery_649['ticket'].head()

0    {3, 41, 11, 12, 43, 14}
1    {33, 36, 37, 39, 8, 41}
2     {1, 6, 39, 23, 24, 27}
3     {3, 9, 10, 43, 13, 20}
4    {34, 5, 14, 47, 21, 31}
Name: ticket, dtype: object

Below, we write the `check_historical_occurrence()` function that takes in the user numbers and the historical numbers and prints information with respect to the number of occurrences and the probability of winning in the next drawing.

In [77]:
def check_historical_occurence(ticket, series):
    ticket_set = set(ticket)
    occurence = (series == ticket_set).sum()
    
    if occurence == 0:
        print("Your ticket number {} has never occured in the past and there aren't any chances of it appearin now, so your chances of winning the big prize is {:.7f}%. \nIn other words, you have 1 in {:,} chances of winning the big prize.".format(ticket, (1/combinations(49,6)*100), int(combinations(49,6))))

    else:
        print("Your ticket number {} has occured {} times in the past, so your chances of winning the big prize is {:.7f}%. \nIn other words, you have {} in {:,} chances of winning the big prize.".format(ticket, occurence, (1/combinations(49,6)*100), occurence, int(combinations(49,6))))

In [78]:
check_historical_occurence([3,41,43,12,11,14], lottery_649['ticket'])

Your ticket number [3, 41, 43, 12, 11, 14] has occured 1 times in the past, so your chances of winning the big prize is 0.0000072%. 
In other words, you have 1 in 13,983,816 chances of winning the big prize.


In [79]:
check_historical_occurence([3,40,43,12,11,14], lottery_649['ticket'])

Your ticket number [3, 40, 43, 12, 11, 14] has never occured in the past and there aren't any chances of it appearin now, so your chances of winning the big prize is 0.0000072%. 
In other words, you have 1 in 13,983,816 chances of winning the big prize.


We have created *extra_numbers* function to create a series of set of ticket numbers occured in the past. 
Also, we have created *check_historical_occurence* function to check whether the user selected numbers occured in the past for the big prize and it tells the user how much of a chance he/she have towards winning the big prize.

## Multi-ticket Probability

For the first version of the app, users should also be able to find the probability of winning if they play multiple different tickets. For instance, someone might intend to play 15 different tickets and they want to know the probability of winning the big prize.

The engineering team wants us to be aware of the following details when we're writing the function:

- The user will input the number of different tickets they want to play (without inputting the specific combinations they intend to play).
- Our function will see an integer between 1 and 13,983,816 (the maximum number of different tickets).
- The function should print information about the probability of winning the big prize depending on the number of different tickets played.

The `multi_ticket_probability()` function below takes in the number of tickets and prints probability information depending on the input.

In [16]:
def multi_ticket_probability(n):
    p_outcomes = combinations(49,6)
    s_outcomes = n
    prob = s_outcomes / p_outcomes
    percentage_prob = prob * 100
    
    return ('You have chosen {} ticket/s, which have a {:7f}% chance of winning the big prize. In other words, you have {:,} chances out of a total of 13,983,816.'.format(n, percentage_prob, n))

In [17]:
for i in [1, 10, 100, 10000, 1000000, 6991908, 13983816]:
    probability = multi_ticket_probability(i)
    print(str(i) + ' ticket/s: ' + probability + '\n')
    print('--------------------------------------')

1 ticket/s: You have chosen 1 ticket/s, which have a 0.000007% chance of winning the big prize. In other words, you have 1 chances out of a total of 13,983,816.

--------------------------------------
10 ticket/s: You have chosen 10 ticket/s, which have a 0.000072% chance of winning the big prize. In other words, you have 10 chances out of a total of 13,983,816.

--------------------------------------
100 ticket/s: You have chosen 100 ticket/s, which have a 0.000715% chance of winning the big prize. In other words, you have 100 chances out of a total of 13,983,816.

--------------------------------------
10000 ticket/s: You have chosen 10000 ticket/s, which have a 0.071511% chance of winning the big prize. In other words, you have 10,000 chances out of a total of 13,983,816.

--------------------------------------
1000000 ticket/s: You have chosen 1000000 ticket/s, which have a 7.151124% chance of winning the big prize. In other words, you have 1,000,000 chances out of a total of 13,98

## Less Winning Numbers — Function

In most 6/49 lotteries, there are smaller prizes if a player's ticket match two, three, four, or five of the six numbers drawn. This means that players might be interested in finding out the probability of having two, three, four, or five winning numbers — for the first version of the app, users should be able to find those probabilities.

These are the details we need to be aware of when we write a function to make the calculations of those probabilities possible:

- Inside the app, the user inputs:
    - six different numbers from 1 to 49; and
    - an integer between 2 and 5 that represents the number of winning numbers expected
- Our function prints information about the probability of having a certain number of winning numbers

To calculate the probabilities, we tell the engineering team that the specific combination on the ticket is irrelevant and we only need the integer between 2 and 5 representing the number of winning numbers expected. Consequently, we will write a function named `probability_less_6()` which takes in an integer and prints information about the chances of winning depending on the value of that integer.

The function below calculates the probability that a player's ticket matches exactly the given number of winning numbers. If the player wants to find out the probability of having five winning numbers, the function will return the probability of having five winning numbers exactly (no more and no less). The function will not return the probability of having _at least_ five winning numbers.

In [58]:
def probability_less_6(n):
    successful_outcomes = combinations(43, (6-n)) * combinations(6,n)
    possible_outcomes = combinations(49,6)
    probability = successful_outcomes / possible_outcomes
    prob_percent = probability * 100
    
    return ('Your chances of having {} winning numbers are {:.6f}%. In other words, you have {:,} in 13,983,816 chances of winning'.format(n, prob_percent, int(successful_outcomes)))

In [63]:
for i in range(2,6):
    print(probability_less_6(i),'\n')
    print('--------------------------')

Your chances of having 2 winning numbers are 13.237803%. In other words, you have 1,851,150 in 13,983,816 chances of winning 

--------------------------
Your chances of having 3 winning numbers are 1.765040%. In other words, you have 246,820 in 13,983,816 chances of winning 

--------------------------
Your chances of having 4 winning numbers are 0.096862%. In other words, you have 13,545 in 13,983,816 chances of winning 

--------------------------
Your chances of having 5 winning numbers are 0.001845%. In other words, you have 258 in 13,983,816 chances of winning 

--------------------------


## Next steps

For the first version of the app, we coded four main functions:

- `one_ticket_probability()` — calculates the probability of winning the big prize with a single ticket
- `check_historical_occurrence()` — checks whether a certain combination has occurred in the Canada lottery data set
- `multi_ticket_probability()` — calculates the probability for any number of of tickets between 1 and 13,983,816
- `probability_less_6()` — calculates the probability of having two, three, four or five winning numbers exactly